name: CaloDiffusion
channels:
  - pytorch
  - conda-forge
  - nvidia/label/cuda-11.3.1
dependencies:
  - python=3.9.19
  - cudatoolkit=11.3
  - cuda-nvcc
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu111
    - torch==1.9.1+cu111
    - h5py
    - tqdm
    - numpy
    - einops
    - joblib
    - PyYAML
    - torchinfo
    - matplotlib